spring:
  datasource:
    url: jdbc:mariadb://ssafy.c9weq5esl3km.ap-northeast-2.rds.amazonaws.com/AwA
    username: ssafy
    password: ssafy1234
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
    generate-ddl: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

