spring:
  datasource:
    url: jdbc:mariadb://awa.cwesz7tzcefm.ap-northeast-2.rds.amazonaws.com/AwA
    username: ssafy
    password: tpwlslrnldudnj!#%
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          #show_sql: true
          format_sql: true
    #generate-ddl: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


