
spring:
  datasource:
    url: jdbc:mariadb://i7c101.p.ssafy.io/AwA
    username: AwA
    password: tpwlslrnldudnj!#%
    driver-class-name: org.mariadb.jdbc.Driver


  #spring:
#  datasource:
#    url: jdbc:mariadb://awa.cwesz7tzcefm.ap-northeast-2.rds.amazonaws.com/AwA
#    username: ssafy
#    password: tpwlslrnldudnj!#%
#    driver-class-name: org.mariadb.jdbc.Driver

  #main:
    #allow-circular-references: true 서로 참조하는 무한루프에서 빠져나오기 위한것이였는데 뭐였더라.. userService내에서 jwtTokenProvider쓰고 JwtTokenProvider에서 userService또불러서 썼는데 걍 userRepository 쓰는걸로 해결
    #무한루프는 양방향 일 때 컨트롤러에서 엔티티를 반환하는 경우 문제 가 생길 수 있다.
    port:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          #show_sql: true
          format_sql: true
    #generate-ddl: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimsejin159@gmail.com
    password: wcoonqgxuqzfloqg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace



